# Generated by Django 4.2.3 on 2023-08-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('U', 'Urbano'), ('R', 'Rural')], max_length=1)),
                ('numero_catastral', models.CharField(max_length=30, unique=True)),
                ('numero_matricula', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'Número de identificación tributaria'), ('TI', 'Tarjeta de Identidad')], max_length=3)),
                ('numero_identificacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídico')], max_length=10)),
                ('predios', models.ManyToManyField(blank=True, to='ARkandha_app.predio')),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioPredio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARkandha_app.predio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARkandha_app.propietario')),
            ],
        ),
        migrations.AddField(
            model_name='predio',
            name='propietarios',
            field=models.ManyToManyField(blank=True, to='ARkandha_app.propietario'),
        ),
    ]
