# Generated by Django 4.2.3 on 2023-08-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARkandha_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='id',
        ),
        migrations.AlterField(
            model_name='predio',
            name='numero_catastral',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
